### ISSUE TITLE
Bugs in code

### ISSUE THREAD

**Issue by kbrotman** [colinskow/move37#1]
Colin,

Please check your code for ars.py.  There seems to be some bugs:

Line 90:  np.random.seed(self.hp.seed)

Lines 156-162: They are indented to much, some lines will need rework as a result of fixing that.

**Comment by colinskow** [comment]
Line 90 is correct and sets the random seed for Numpy. Lines 158-162 are correct since they are inside an IF statement.

**Comment by kbrotman** [comment]
I see.  I had handwritten Lines 156-162 indented incorrectly.  Line 90 I didn't understand.  Thanks.
